version: "2.1"
services:
  appsrv:
    build:
      dockerfile: Dockerfile.allinone
      context: .
    volumes:
      - ./unicorn.rb.compose:/app/unicorn.rb
    mem_limit: 100M
    cpu_shares: 1000
    command: unicorn -c unicorn.rb
  web:
    build:
      dockerfile: Dockerfile.allinone
      context: .
    volumes:
      - ./nginx.conf.compose:/etc/nginx/nginx.conf
    depends_on:
      - appsrv
    ports:
      - 8080:8080
    mem_limit: 50M
    cpu_shares: 500
    command: nginx -g 'daemon off;'
